### ISSUE TITLE
这本册子的排版是不是参考了潮语拼音教程呀

### ISSUE THREAD

**Issue by kahaani** [leimaau/naambaakbook#1]
请问这本册子的排版是不是参考了[潮语拼音教程](https://github.com/Kahaani/gatian)呀？:smile:

我发现在1.2节有引用到。

**Comment by leimaau** [comment]
是的，受惠于你的潮语拼音教程的启发，我才能完成自己的这份教程，不过我的教程主旨不是教授拼音方案，而是把我原来博客的文章整理，介绍南宁白话的基础知识，主要借鉴了潮语拼音教程的目录框架，没能及时向你表示感谢，深表谦意。1.2节的引用其实更早是在我其他博客中的文章中的，后来复制到我的这份教程中，当时写得匆忙所以比较乱，后续的更新中我会考虑把潮语拼音教程列到新开的致谢栏中。 若是有任何建议和意见也欢迎提出。

**Comment by kahaani** [comment]
谢谢答复。

之前尝试从 GitBook 2.x 升级到 3.x 但不太习惯，看了你的教程觉得 3.x 的效果还不错。:thumbsup:
